In [2]:
import pandas as pd
data = [1, 2, 3, 4, 5]
data = pd.Series(data)
print(data)
print(type(data))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [3]:
###creating a series from dictionary
##series is a one dimensional array like object that can hold any data types.It is similar to a column in a table
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [4]:
#can be written this way too
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [5]:
##Dataframe
data={
    'Name':['krish','john','jack'],
    'Age':[25,34,55],
    'city':['bangalore','nweyork','florida']
}
print(data)
print(pd.DataFrame(data))

{'Name': ['krish', 'john', 'jack'], 'Age': [25, 34, 55], 'city': ['bangalore', 'nweyork', 'florida']}
    Name  Age       city
0  krish   25  bangalore
1   john   34    nweyork
2   jack   55    florida

In [6]:
##creating a data frame from a list of dictionaries
data=[
    {'Name':'krishna','Age':32,'city':'damauli'},
    {'Name':'adhyaya','Age':36,'city':'rampur'},
    {'Name':'akrit','Age':45,'city':'dolakha'}
     
]
print(pd.DataFrame(data))

      Name  Age     city
0  krishna   32  damauli
1  adhyaya   36   rampur
2    akrit   45  dolakha

In [7]:
df=pd.read_csv('sales_data.csv')
print(df.head(5))
df.head(5)

   Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum
2           10003  2024-01-03         Clothing         Levi's 501 Jeans
3           10004  2024-01-04            Books        The Da Vinci Code
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set

   Units Sold  Unit Price  Total Revenue         Region Payment Method
0           2      999.99        1999.98  North America    Credit Card
1           1      499.99         499.99         Europe         PayPal
2           3       69.99         209.97           Asia     Debit Card
3           4       15.99          63.96  North America    Credit Card
4           1       89.99          89.99         Europe         PayPal

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [8]:
df['Region']#returns a series

0      North America
1             Europe
2               Asia
3      North America
4             Europe
           ...
235           Europe
236             Asia
237    North America
238           Europe
239             Asia
Name: Region, Length: 240, dtype: str

In [9]:
df[['Region']]

            Region
0    North America
1           Europe
2             Asia
3    North America
4           Europe
..             ...
235         Europe
236           Asia
237  North America
238         Europe
239           Asia

[240 rows x 1 columns]

In [10]:
print(type(df[['Region']]))
type(df['Region'])

<class 'pandas.DataFrame'>

pandas.Series

In [11]:
df.loc[0]#gives value of row 0

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [12]:
df.loc[1]

Transaction ID                 10002
Date                      2024-01-02
Product Category     Home Appliances
Product Name        Dyson V11 Vacuum
Units Sold                         1
Unit Price                    499.99
Total Revenue                 499.99
Region                        Europe
Payment Method                PayPal
Name: 1, dtype: object

In [13]:
df.iloc[0]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [14]:
df.at[2,'Date']#sees row 2 and date column

'2024-01-03'

In [18]:
df.head(3)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card

In [ ]:
df.iat[2,2]###we can give row index and column index over here

'Clothing'

In [21]:
###data manipulation with data frame
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
df['Dates'] = '2024-01-04'###adding a column
df.head(4)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Dates
0,10001,2024-01-04,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,2024-01-04
1,10002,2024-01-04,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,2024-01-04
2,10003,2024-01-04,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,2024-01-04
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,2024-01-04

In [ ]:
###Remove a column
df.drop('Dates',axis=0)##axis 0 checks if rowexists there or not of name Dates

KeyError: "['Dates'] not found in axis"

In [ ]:
df.drop('Dates',axis=1)#dates column gets deleted

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-04,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-04,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-04,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-04,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-01-04,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-01-04,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-01-04,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-01-04,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-01-04,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [32]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Dates
0,10001,2024-01-04,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,2024-01-04
1,10002,2024-01-04,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,2024-01-04
2,10003,2024-01-04,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,2024-01-04
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,2024-01-04
4,10005,2024-01-04,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,2024-01-04
...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-01-04,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,2024-01-04
236,10237,2024-01-04,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,2024-01-04
237,10238,2024-01-04,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,2024-01-04
238,10239,2024-01-04,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,2024-01-04
239,10240,2024-01-04,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,2024-01-04

In [ ]:
###to make the change permanent we use inplace
df.drop('Date',axis=1,inplace=True)
df

,Transaction ID,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method
0,10001,Electronics,iPhone 14 Pro,2,999.99,1999.98,Credit Card
1,10002,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,PayPal
2,10003,Clothing,Levi's 501 Jeans,3,69.99,209.97,Debit Card
3,10004,Books,The Da Vinci Code,4,15.99,63.96,Credit Card
4,10005,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,PayPal
...,...,...,...,...,...,...,...
235,10236,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,PayPal
236,10237,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Debit Card
237,10238,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,Credit Card
238,10239,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,PayPal
239,10240,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Credit Card

In [ ]:
df.head(5)

,Transaction ID,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method
0,10001,Electronics,iPhone 14 Pro,2,999.99,1999.98,Credit Card
1,10002,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,PayPal
2,10003,Clothing,Levi's 501 Jeans,3,69.99,209.97,Debit Card
3,10004,Books,The Da Vinci Code,4,15.99,63.96,Credit Card
4,10005,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,PayPal

In [43]:
# Fix the capitalization to 'Product Category' and add 's' to index 0 and 1
df.loc[0:1, 'Product Category'] = df.loc[0:1, 'Product Category'] + 's'

# View the changes
df.head(5)

,Transaction ID,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method
0,10001,Electronicss,iPhone 14 Pro,2,999.99,1999.98,Credit Card
1,10002,Home Appliancess,Dyson V11 Vacuum,1,499.99,499.99,PayPal
2,10003,Clothing,Levi's 501 Jeans,3,69.99,209.97,Debit Card
3,10004,Books,The Da Vinci Code,4,15.99,63.96,Credit Card
4,10005,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,PayPal

In [48]:
df.loc[0:1,'Transaction ID']

0    10001
1    10002
Name: Transaction ID, dtype: int64

In [54]:
df.iloc[0,2]

'iPhone 14 Pro'

In [52]:
###displaying the data types of each column
df.dtypes

Transaction ID        int64
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Payment Method          str
dtype: object

In [ ]:
### describe the data frame
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000